config/routes.rb
Xero::Application.routes.draw do

  root :to => 'welcome#index'

  get "welcome/index"
  
  resources :invoices

  resources :xero_session

  resources :users

  resources :accounts
  

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @directory = Rails.root.join("privatekey.pem");
    @client = Xeroizer::PrivateApplication.new("YFTECYJPUVN6BTEVOF2MIQ3RUSOMWU", "HOE5NA89VTD65LXLWRKRETSRFYNMTH", @directory)

    @accounts = @client.Account.all(:where => 'Type=="BANK"')
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  def index 
    @directory = Rails.root.join("privatekey.pem");
    @client = Xeroizer::PrivateApplication.new("YFTECYJPUVN6BTEVOF2MIQ3RUSOMWU", "HOE5NA89VTD65LXLWRKRETSRFYNMTH", @directory)

    @invoices = @client.Invoice.all

    @clients = @client.Contact.all(:order => 'Name') 

  end


end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    
  @directory = Rails.root.join("privatekey.pem");
  @client = Xeroizer::PrivateApplication.new("YFTECYJPUVN6BTEVOF2MIQ3RUSOMWU", "HOE5NA89VTD65LXLWRKRETSRFYNMTH", @directory)

  @contacts = @client.Contact.all

  end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/xero_session_controller.rb
class XeroSessionController < ApplicationController
  
  before_filter :get_xero_client

  public

    def new
      request_token = @xero_client.request_token(:oauth_callback => 'http://localhost:3000/oauth/callback')
      session[:request_token] = request_token.token
      session[:request_secret] = request_token.secret

      redirect_to request_token.authorize_url
    end

    def create
      @xero_client.authorize_from_request(
              session[:request_token], 
              session[:request_secret], 
              :oauth_verifier => params[:oauth_verifier] )

      session[:xero_auth] = {
              :access_token => @xero_client.access_token.token,
              :access_key => @xero_client.access_token.key }

      session.data.delete(:request_token)
      session.data.delete(:request_secret)
    end

    def destroy
      session.data.delete(:xero_auth)
    end

  private

    def get_xero_client
      @xero_client = Xeroizer::PublicApplication.new("LKNYBYIJY0PC36D0OKIA5X9REHV8VH", "I4OKGBJSLR79AJBBVEFELHPZQFNCOH")

      # Add AccessToken if authorised previously.
      if session[:xero_auth]
        @xero_client.authorize_from_access(
          session[:xero_auth][:access_token], 
          session[:xero_auth][:access_key] )
      end
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/xero_session_helper.rb
module XeroSessionHelper
end

app/views/accounts/index.html.erb
<div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
          <div class="table-responsive">
              <h3>List of Available Bank Accounts</h3>
                <p>There are <%= @accounts.count %> accounts available: </p>
                  <% @accounts.each do |account| %>
                   <ul>
                     <li>Account Name: <%= account.name %> ("<%=account.currency_code %>")</li>
                     <li>Account Number: <%= account.bank_account_number%></li>
                   </ul>
                    <% end %> 
          </div>
       </div>
    </div>      
</div>

app/views/invoices/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <h1>List of Invoice numbers with amounts outstanding</h1>

              <% @invoices.each do |i| %>

              <ul>
                <li><%= i.invoice_id %></li>
              </ul>

              <br>

              <% end %>
        </div>
    </div>
</div>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xero API Tool</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-8">
          <ul class="nav navbar-nav">
            <li>
              <a href="/">Xero API Tool</a> 
            </li>
            <li>
                 <a href="/users">Contacts</a> 
            </li>
            <li>
                 <a href="/invoices">Invoices</a>
            </li>
            <li>
                 <a href="/accounts">Bank Accounts</a>
            </li>
          </ul>
        </div>
      </div>
  </div>
</nav>

<body>
    
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
          <div class="table-responsive">
              <table class="table table-striped">
                  <h3>Listing all Contact in the Database<h3> 
                    <% @contacts.each do |contact| %>
                       <tr>
                        <th>Contact Name</th>
                        <th>Email</th>
                        <th>Bank Account Details</th>
                      </tr>
                        <td><%= contact.name %></td>
                        <td> <%= contact.email_address %></td>
                        <td><%= contact.bank_account_details %></td>
                        <% end %> 
              </table> 
          </div>
      </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
          <p><%= link_to "List of Contacts in the Database", users_path %></p> 
          <p><%= link_to "List of Invoices", invoices_path %></p>
          <p><%= link_to "List of Bank Accounts", accounts_path %></p>
        </div>
    </div>
</div>                                